apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplepod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplepod
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":"ctrlpub0","ips":["100.77.142.66/26","2a00:8a00:4000:d11:4::1202/119"],"interface":"ctrlpub0"}]'
      labels:
        app: samplepod
    spec:
      containers:
      - name: samplepod
        image: alpine
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
