apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ctrlpub0
  namespace: case03813180
spec:
  config: '{
    "cniVersion":"0.3.1",
    "ipam":{
       "routes":[{"dst":"10.10.200.0/22","gw":"100.77.142.65"},{"dst":"100.103.82.128/25","gw":"100.77.142.65"},{"dst":"2A00:8A00:4000:020C:0000:0000:017E:0000/112","gw":"2A00:8A00:4000:0D11:4::1201"}],"type":"static"},
    "master":"tenant-vlan.119",
    "mode":"l2",
    "mtu":1500,
    "name":"ctrlpub0",
    "type":"ipvlan"}'
