apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-nm-trace-logging
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,W2xvZ2dpbmddCmRvbWFpbnM9QUxMOlRSQUNFCg==
        mode: 0644
        overwrite: true
        path: /etc/NetworkManager/conf.d/99-nm-trace-logging.conf
