apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond0-ens8-ens9-policy 
spec:
  nodeSelector: 
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
    - name: tenant-bond1
      description: Bond with ports ens8 and ens9
      type: bond 
      state: up 
      link-aggregation:
        mode: active-backup 
        options:
          miimon: '100' 
        port: 
        - ens8
        - ens9
      mtu: 9126
