apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"name":"ctrlpub0","ips":["100.77.142.66/26","2a00:8a00:4000:d11:4::1202/119"],"interface":"ctrlpub0"}]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
